# Generated by Django 6.0.6 on 2026-06-22 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_residence', models.CharField(default='Résidences Bereby', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, default=4.7833, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=-7.05, max_digits=9)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone_principal', models.CharField(blank=True, max_length=30)),
                ('numero_orange_money', models.CharField(blank=True, max_length=30)),
                ('numero_mtn_money', models.CharField(blank=True, max_length=30)),
                ('numero_wave', models.CharField(blank=True, max_length=30)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('lien_facebook', models.URLField(blank=True)),
                ('lien_instagram', models.URLField(blank=True)),
                ('lien_whatsapp', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Studio Vue Mer 1', max_length=100)),
                ('type_unite', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('local_commercial', 'Local commercial')], default='studio', max_length=20)),
                ('etage', models.IntegerField(choices=[(0, 'Sous-sol'), (1, '1er étage'), (2, '2e étage'), (3, '3e étage')])),
                ('vue_mer', models.BooleanField(default=False)),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capacite_personnes', models.PositiveIntegerField(default=2)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['etage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150)),
                ('email_client', models.EmailField(max_length=254)),
                ('telephone_client', models.CharField(max_length=30)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('nombre_personnes', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='residences.unite')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unites/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('principale', models.BooleanField(default=False, help_text='Photo affichée en premier')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='residences.unite')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=100)),
                ('nom_en', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône (ex: wifi, tv, ac)", max_length=50)),
                ('unites', models.ManyToManyField(blank=True, related_name='equipements', to='residences.unite')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
    ]
