# Generated by Django 6.0.6 on 2026-07-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_villecle'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='nom_fr_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nom_fr_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='adresse_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='adresse_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='nom_residence_en',
            field=models.CharField(default='Résidences Bereby', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='nom_residence_fr',
            field=models.CharField(default='Résidences Bereby', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='nom_en',
            field=models.CharField(help_text='Ex: Studio Vue Mer 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unite',
            name='nom_fr',
            field=models.CharField(help_text='Ex: Studio Vue Mer 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='villecle',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='villecle',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unite',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
