# Generated by Django 6.0.6 on 2026-07-28 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_reservation_code_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='residences.unite')),
            ],
            options={
                'verbose_name': 'Abonnement disponibilité',
                'verbose_name_plural': 'Abonnements disponibilité',
                'ordering': ['-date_inscription'],
                'unique_together': {('unite', 'email')},
            },
        ),
    ]
