# Generated by Django 6.0.6 on 2026-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_abonnementdisponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='indicatif_regional',
            field=models.CharField(blank=True, help_text="Ex: +225 (Côte d'Ivoire)", max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='moyen_communication',
            field=models.CharField(choices=[('email', 'Email'), ('appel', 'Appel téléphonique'), ('whatsapp', 'WhatsApp')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='moyen_paiement',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire (Visa/Mastercard)'), ('sur_place', 'Paiement sur place')], default='sur_place', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preuve_paiement',
            field=models.ImageField(blank=True, help_text="Capture d'écran du paiement (Mobile Money)", null=True, upload_to='preuves_paiement/'),
        ),
    ]
