# Generated by Django 6.0.6 on 2026-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0006_reservation_indicatif_regional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_paiement',
            field=models.DateTimeField(blank=True, help_text='Date du paiement en ligne', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paiement_reference',
            field=models.CharField(blank=True, help_text='Référence de la transaction CinetPay', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paiement_statut',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('en_attente', 'Paiement en attente'), ('effectue', 'Paiement effectué'), ('refuse', 'Paiement refusé')], default='non_paye', help_text='Suivi du paiement par carte (CinetPay)', max_length=20),
        ),
    ]
